pool:
  vmImage: ubuntu-20.04

name: FE-SERVICE-E2E

trigger: none

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: true
    retryCountOnTaskFailure: 2

  - bash: |
      echo "Running Cypress Test"
      export CYPRESS_APPURL=http://40.127.211.136/
      npx cypress run --browser chrome --reporter junit --reporter-options "mochaFile=./cypress/results/TEST-bpfeservice-Result.xml,toConsole=true"
    displayName: 'Cypress Test'
    continueOnError: false

  - task: PublishTestResults@2
    displayName: 'Publish Test Results ead-ca2-bp-fe-service'
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'FE-SERVICE-E2T'
