# test deploy in kubernates

trigger:
  - None

pool:
  vmImage: ubuntu-latest
variables:
  ACR.Name: 'ainhabacr'
  Azure.ServiceConnection: 'ainhabacrconnection'
steps:
  # - task: HelmInstaller@1
  #   displayName: 'installHelm'
  #   inputs:
  #     helmVersionToInstall: 'latest'
  - task: AzureCLI@2
    displayName: 'Login to Azure Container Registry'
    inputs:
      azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(ACR.Name).azurecr.io
        az acr helm repo add -n $(ACR.Name).azurecr.io
        az acr repository show --name $(ACR.Name) --repository charts/bp_info_service
        az acr helm repo update
        az acr helm install bp_info_service oci://$(ACR.Name).azurecr.io/charts/bp_info_service --version 1.0.0
  # - task: HelmDeploy@0
  #   inputs:
  #     connectionType: 'Azure Resource Manager'
  #     azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
  #     azureResourceGroup: 'k8s-resource-group'
  #     kubernetesCluster: 'ainhabAKSCluster'
  #     namespace: 'default'
  #     command: 'install'
  #     chartType: 'Name'
  #     chartName: '$(ACR.Name).azurecr.io/charts/bp_info_service'
  #     chartVersion: '1.0.0'