# test deploy in kubernates

trigger:
  - None

pool:
  vmImage: ubuntu-latest
steps:
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
    azureResourceGroup: 'k8s-resource-group'
    kubernetesCluster: 'ainhabAKSCluster'
    namespace: 'default'
    command: 'install'
    chartType: 'Name'
    chartName: 'charts/bp_info_service'
    chartVersion: '1.0.0'