# test deploy in kubernates

trigger:
  - None

pool:
  vmImage: ubuntu-latest
variables:
  ACR.Name: 'ainhabacr'
  Azure.ServiceConnection: 'ainhabacrconnection'
steps:
  - task: HelmInstaller@0
    displayName: 'installHelm'
    inputs:
      helmVersion: 3.9.3
      kubectlVersion: 1.26.3
  - task: AzureCLI@2
    displayName: 'Login to Azure Container Registry'
    inputs:
      azureSubscription: 'Azure for Students(7263e463-da66-4888-a897-f34f5acea14b)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(ACR.Name).azurecr.io
  - task: HelmDeploy@0
    displayName: 'helm upgrade or install ap'
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: 52e7b636-9ce7-4f7d-be99-3bb1c59c1584
      namespace: default
      command: 'install'
      chartType: Name
      chartName: 'oci://$(ACR.Name).azurecr.io/charts/bpinfoservice'
      releaseName: bpinfoservice
      upgradetiller: false
      save: false
      install: false
      arguments: --timeout 1m
