apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-fe-app
  labels:
    app: bpfeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpfeapp
  template:
    metadata:
      labels:
        app: bpfeapp
    spec:
      containers:
        - image: ainhabacr.azurecr.io/eadca2/bpfeapplication:v1
          name: bpfeapplication
          imagePullPolicy: Always
          ports:
            - containerPort: 32137
          env:
            - name: PROFILE
              value: {{ .Values.profile }}
            - name: SPACE
              value: {{ .Values.space }}
