apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: bpfesvc
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  # type: LoadBalancer
  type: {{ .Values.befesvc.serviceType }}
  ports:
    - name: http
      port: {{ .Values.befesvc.port }}
      targetPort: {{ .Values.befesvc.targetPort }}
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: bpfeapp
